### PR TITLE
[Woo] Fix Site Credentials login when site discovery fails and site has http to https redirection

### LINKED ISSUE #11931: Login failures when using site credentials due to URL redirections.
# Issue
During the authentication steps using the Application Password credentials, some redirections might happen as the URL changes between http and https. 

Currently, our network request API is not configured to pass forward the request header, making the credentials unavailable and failing the authentication process.

# Possible solutions
The solution for this can be achieved from two approaches:

1. Use a request header forwarding strategy inside the ApplicationPasswordsNetwork by supplying the RequestQueue with the name custom-ssl-custom-redirects. However, this would require deeper research on any potential regressions.

2. Make changes to how we infer https websites. WCiOS already treats all websites as SSL-ready and displays an error for sites that don't. Android could follow the same approach.

### PR DESCRIPTION
**Pull request by hichamboushaba**
Closes: https://github.com/woocommerce/woocommerce-android/issues/11931

This PR updates the logic of site discovery used to infer the `SiteModel#wpApiRestUrl` to use `https` by default when the automatic discovery fails, this fixes login issues for sites with non-working discovery (non-standard `Link` header) and `http` to `https` redirection, for more information, please check peaMlT-Kc-p2

For tests, please check the PR https://github.com/woocommerce/woocommerce-android/pull/12033

### CODE REVIEW

File: fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/WPAPIDiscoveryUtils.kt [hunk 1]
```diff
@@ -0,0 +1,18 @@
...
+
+internal object WPAPIDiscoveryUtils {
+    fun buildDefaultRESTBaseUrl(
+        url: String
+    ): String {
+        val urlWithoutScheme = UrlUtils.removeScheme(url)
+        val httpsUrl = UrlUtils.addUrlSchemeIfNeeded(urlWithoutScheme, true)
+
+        // TODO investigate the possibility to use `/?rest_route=` instead,
+        //  `/wp-json` works only when permalinks are enabled, where `/?rest_route=` works without them
```
Comment (hichamboushaba) [inline fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpapi/WPAPIDiscoveryUtils.kt:14]: I added this TODO to keep track of the explained issue, I also logged this Github issue to keep track of it https://github.com/woocommerce/woocommerce-android/issues/12043

**Review by JorgeMucientes — APPROVED** [review]
