### PR TITLE
Issue/1061 missing data error

### LINKED ISSUE #1061: Treat missing Overview data as an error
Treat the missing `period` and `dates` parameters as an error. The timed stats without these parameters don't make sense and passing empty data can cause unexpected errors in the client.

### PR DESCRIPTION
**Pull request by 0nko**
Fixes #1061.

### CODE REVIEW

File: fluxc/src/main/java/org/wordpress/android/fluxc/model/stats/time/TimeStatsMapper.kt [hunk 1]
```diff
@@ -108,7 +108,7 @@ class TimeStatsMapper
             }
         }
         if (response.data == null) {
```
Comment (planarvoid) [inline fluxc/src/main/java/org/wordpress/android/fluxc/model/stats/time/TimeStatsMapper.kt]: do you think it makes sense to have here `if (response.data == null || dataPerPeriod == null)` in order to log the other case when we have only invalid in the response?
