### PR TITLE
[Detekt Baseline Warnings] FluxC Module - Resolve/Suppress Complexity & Naming Warnings

### LINKED ISSUE #2485: Resolve/Suppress Detekt Baseline Warnings - FluxC Module
Parent #2479

This issue is about resolving/suppressing the Detekt related warnings that are within Detekt's [baseline](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/config/detekt/baseline.xml) for the `fluxc` module.

Number of Warnings: `283`

### Tasks

- [x] Resolve/Suppress `style` related warnings. @ParaskP7 #2490
    - style (`132`) ✅
        1. DataClassShouldBeImmutable (`70`) ✅
        2. ExplicitItLambdaParameter (`1`) ✅
        3. ForbiddenComment (`10`) ✅
        4. MagicNumber (`18`) ✅
        5. MaxLineLength (`15`) ✅
        6. ReturnCount (`10`) ✅
        7. UnnecessaryAbstractClass (`1`) ✅
        8. UnusedPrivateMember (`4`) ✅
        9. UseCheckOrError (`1`) ✅
        10. UtilityClassWithPublicConstructor (`2`) ✅
- [x] Resolve/Suppress `complexity/naming` related warnings. @ParaskP7 #2491 (with [comment](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2491#discussion_r943548751), cc @irfano)
    - complexity (`59`) ✅
        1. ComplexCondition (`6`) ✅
        2. ComplexMethod (`14`) ✅
        3. LargeClass (`4`) ✅
        4. LongMethod (`6`) ✅
        5. LongParameterList (`21`) ✅
        6. NestedBlockDepth (`8`) ✅
    - naming (`51`) ✅
        1. ConstructorParameterNaming (`31`) ✅
        2. VariableNaming (`20`) ✅
- [x] Resolve/Suppress `coroutines/empty-blocks/exceptions/performance/potential-bugs` related warnings. @ParaskP7 #2493
    - coroutines (`2`) ✅
        1. GlobalCoroutineUsage (`2`) ✅ (with [comment](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1605#issuecomment-1210609730), cc @khaykov @develric) 
    - empty-blocks (`1`) ✅
        1. EmptyFunctionBlock (`1`) ✅
    - exceptions (`33`) ✅
        1. SwallowedException (`23`) ✅
        2. TooGenericExceptionCaught (`8`) ✅
        3. TooGenericExceptionThrown (`2`) ✅
    - performance (`4`) ✅
        1. SpreadOperator (`4`) ✅
    - potential-bugs (`1`) ✅
        1. ImplicitDefaultLocale (`1`) ✅

### PR DESCRIPTION
**Pull request by ParaskP7**
Parent #2479
Partially Closes: #2485

This PR resolves/suppresses all `complexity` and `naming` related warnings for the `fluxc` module:

- `59` x complexity
    1. `6` x ComplexCondition (Resolve: 6bee094fce82a9395e81e3db309cba44f7b29f95 + Suppress: 11308f56b2b4de608c84a568c94253c5f5a9cc8d)
    2. `14` x ComplexMethod (Resolve: c13914cbf9aa742bd51849fcdbbe237b829fcdfe + Suppress: e7556975ebcccd755f06a2d49e3610b3b6909811 + 3c13e594043c51cbb0f4dbeda5fefbc8d2434d11)
    3. `4` x LargeClass (Suppress: 13743875195599f107e18067210122a3eb2452ae)
    4. `6` x LongMethod (Suppress: cace7134f5a853c5be73c765a9cdf611146bc6c9)
    5. `21` x LongParameterList (Suppress: 96876e2aa1e7525b0e482238feb152ed1c910913)
    6. `8` x NestedBlockDepth (Resolve: bc4768c57b57ef0678c0f6ee4bc81c1771133c28 + Suppress: bc67aa2e0e4c16e1c3fe348916557f2062f06e7f)
- `51` x naming
    1. `31` x ConstructorParameterNaming (Suppress: a7553aa6ca12e966cf12eba56e019c5f069354ac)
    2. `20` x VariableNaming (Resolve: 8ef999cb2da951f270b293ac276a5ef41977b9b7 + Suppress: 8576358288f33279102620184e709f56f1030d3f)

PS.1: I am randomly adding one engineer from the WPAndroid team and one from the WCAndroid team as the main reviewers, that is, in addition to the @wordpress-mobile/owl-team team itself, since I just want someone from these teams to ~~sing-off (😅)~~ sign-off on that change as well (or additionally to the 🦉 team).

PS.2: I recommend reviewing this PR commit-by-commit.

-----

To test:

- There is nothing much to test here.
- Verifying that all the CI checks are successful should be enough (especially the `detekt` check).
- However, if you really want to be thorough, you could smoke test the `example` and/or the `WPAndroid/WCAndroid` apps to verify that everything works as expected.

PS: Please ignore the failing `connected-tests` check as they are unrelated to this PR. This check has been failing consistency for some time now due to tests being flaky or needing to be updated/fixed.

### CODE REVIEW

File: fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginCoroutineStore.kt [hunk 1]
```diff
@@ -29,11 +29,12 @@ import org.wordpress.android.fluxc.utils.CurrentTimeProvider
...
 import java.net.HttpURLConnection
 import javax.inject.Inject
+import javax.inject.Singleton
 
 private const val PLUGIN_CONFIGURATION_DELAY = 1000L
 
-class PluginCoroutineStore
-@Inject constructor(
+@Singleton
+class PluginCoroutineStore @Inject constructor(
```
Comment (irfano) [inline fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginCoroutineStore.kt]: This is my only concern. Adding `@Singleton` will change the function though it's the correct change. 
But I couldn't find any problem about that.

**Review by irfano — APPROVED** [review]
Well-defined commits. Great job, @ParaskP7!
LGTM! 👍🏻 I'm approving, but UI tests are failing. I'm not sure we can temporarily ignore UI tests like in "WPAndroid".

**Comment by ParaskP7** [comment]
👋 @irfano !

Thank you so much for reviewing and testing this PR! 🥇 🙇 🌟 

> LGTM! 👍🏻 I'm approving, but UI tests are failing. I'm not sure we can temporarily ignore UI tests like in "WPAndroid".

Yes, we can actually safely ignore these connected tests for now (see Slack message: `C02QANACA/p1659504296491789`) and that's why I added this `PS` about them in this PR's description (see below).

```
PS: Please ignore the failing connected-tests check as they are unrelated to this PR. This check has
been failing consistency for some time now due to tests being flaky or needing to be updated/fixed.
```

File: fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginCoroutineStore.kt (hunk 1 above)
Comment (ParaskP7) [reply fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginCoroutineStore.kt]: 👋 @irfano and thank you so much for actually catching that and opening a discussion about it! 🙇 

I also was on the fence about this change, but I chose to progress with it anyway since this is the rule. Yes, it will change the function in terms of it will now be just one instance of this store instead of multiple of them, but this might very well not change the outcome, but then again it might do, though I doubt it betting on the rule, which explicitly states that all stores should be singletons and as such clients should depend on that to be the case.

PS: I am now shamelessly pinging @planarvoid on that since he was the initial and only author of that store. It's been a while since then, a bit more than a year, but he might know if this was done deliberately, that is, to not have this store as singleton.

Comment (ParaskP7) [reply fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginCoroutineStore.kt]: The interesting bit about [this CheckStyle configuration and thus regex](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/config/checkstyle.xml#L84-L88) is the fact that it is **NOT** correctly working when the store `class` and `constructor` are split into two separate lines, like that:

```
class PluginCoroutineStore
@Inject constructor(
    ...
) {
    ...
}
```

It only works if the `class` and `constructor` are on the same line, like this:

```
class PluginCoroutineStore @Inject constructor(
    ...
) {
    ...
}
```

Thus, and because I did this refactor via [this commit](https://github.com/wordpress-mobile/WordPress-FluxC-Android/commit/e7556975ebcccd755f06a2d49e3610b3b6909811#diff-44f37195454337f4b258b698820c5b5fa052a6ee07cc9d21d743e479868b4784), CheckStyle started complaining, triggering me to apply [this additional change](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2491/commits/3c13e594043c51cbb0f4dbeda5fefbc8d2434d11) we are now discussing.

I wonder how many other such store related CheckStyle warnings are currently not being reported because of the `class` and `constructor` being split into two separate lines. 🤔

Comment (ParaskP7) [reply fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginCoroutineStore.kt]: Interestingly enough, I did a global search on `class .*Store` and then checked each store one-by-one to see if we have other such stores that are not defined as singletons. The results is that in addition to [PluginCoroutineStore](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/e5cf7a211c05ac9c2051415b5221924918a0b589/fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginCoroutineStore.kt#L35-L36), we have only 2 other such stores (3 in total, out of hundreds of them), the [SiteOptionsStore](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/e5cf7a211c05ac9c2051415b5221924918a0b589/fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteOptionsStore.kt#L36-L37) and [XPostsStore](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/e2752ac62e012e5ad38ee3ae36acfc506d01ea0b/fluxc/src/main/java/org/wordpress/android/fluxc/store/XPostsStore.kt#L14-L15), and all 3 of them are having their `class` and `constructor` defined into two separate lines. 🤔 

The history on all those 3 stores shows that when those stores were created (initial commit) they were created **WITHOUT** the `@Singleton` annotation. To me this smells that this wasn't intentional, but rather an oversight, especially since CheckStyle wasn't complaining about that (as it should have had). 🤔 x 10

Wdyt?

Cc @irfano @planarvoid

Comment (ParaskP7) [reply fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginCoroutineStore.kt]: Also, from @planarvoid [PR's description here](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/2043) I don't see any mention about `PluginCoroutineStore` and it not being a singleton for some particular reason. Same applies to the other 2 such stores:

- [Add site homepage settings #1583](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1583) for the [SiteOptionsStore](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/e5cf7a211c05ac9c2051415b5221924918a0b589/fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteOptionsStore.kt#L36-L37)
- [Add XPostsStore for Retrieving a site's xpost candidates #1769](https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/1769) for the [XPostsStore](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/e2752ac62e012e5ad38ee3ae36acfc506d01ea0b/fluxc/src/main/java/org/wordpress/android/fluxc/store/XPostsStore.kt#L14-L15)

Comment (irfano) [reply fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginCoroutineStore.kt]: Good findings!
>The interesting bit about [this CheckStyle configuration and thus regex](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/config/checkstyle.xml#L84-L88) is the fact that it is NOT correctly working

Firstly, we can try to fix the regex. Maybe we can open an issue for now, and fix it in another PR.
>The results is that in addition to [PluginCoroutineStore](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/e5cf7a211c05ac9c2051415b5221924918a0b589/fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginCoroutineStore.kt#L35-L36), we have only 2 other such stores (3 in total, out of hundreds of them), the [SiteOptionsStore](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/e5cf7a211c05ac9c2051415b5221924918a0b589/fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteOptionsStore.kt#L36-L37) and [XPostsStore](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/e2752ac62e012e5ad38ee3ae36acfc506d01ea0b/fluxc/src/main/java/org/wordpress/android/fluxc/store/XPostsStore.kt#L14-L15)

I'm trying to understand the use of stores and thinking about why we need to make stores singleton. They don't have any variables that must be the same for consumers. They only have parameters coming from the constructor. And I guess the critical parameters are [`XPostsSqlUtils`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/XPostsSqlUtils.kt) and [`Dispatcher`](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/fluxc/src/main/java/org/wordpress/android/fluxc/Dispatcher.java) because these are writing and emitting results. So, to my understanding, `XPostsSqlUtils` and `Dispatcher` need to be a singleton, and they are already singleton, even in different instances of `PluginCoroutineStore`, for example. I feel like `@Singleton` could be unnecessary, but I haven't tested it. I am just telling my thoughts.
I don't have much experience on this repo, but I'd like to know why the `@Singleton` rule was added in checkstyle.

Comment (ParaskP7) [reply fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginCoroutineStore.kt]: I think for us to unblock this PR but still have this discussion going, I am going to revert this `@Singleton` change for now, merge this PR and open an issue about those 3 stores (them not being singletons) so we can continue the discussion there. Wdyt? 🤔 

> Firstly, we can try to fix the regex. Maybe we can open an issue for now, and fix it in another PR.

I agree, I'll create an additional ticket for that too. 💯 

> I'm trying to understand the use of stores and thinking about why we need to make stores singleton. They don't have any variables that must be the same for consumers. They only have parameters coming from the constructor. And I guess the critical parameters are [XPostsSqlUtils](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/fluxc/src/main/java/org/wordpress/android/fluxc/persistence/XPostsSqlUtils.kt) and [Dispatcher](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/fluxc/src/main/java/org/wordpress/android/fluxc/Dispatcher.java) because these are writing and emitting results. So, to my understanding, XPostsSqlUtils and Dispatcher need to be a singleton, and they are already singleton, even in different instances of PluginCoroutineStore, for example. I feel like @Singleton could be unnecessary, but I haven't tested it. I am just telling my thoughts.
I don't have much experience on this repo, but I'd like to know why the @Singleton rule was added in checkstyle.

Yes, I agree, it seems a bit strange indeed. Maybe we can search on P2s or Slack about that, just to figure out the real reasoning behind that, I am sure there was a good reason... 🤔

Comment (ParaskP7) [reply fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginCoroutineStore.kt]: 👋 @irfano !

> I think for us to unblock this PR but still have this discussion going, I am going to revert this @Singleton change for now, merge this PR...

PS: I reverted this change for now (see 6015d6bdcfb895a6fbb0ddb6b33dff9e677fd088) and will merge this PR as soon as CI completes successfully. ✅

Comment (ParaskP7) [reply fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginCoroutineStore.kt]: > ...and open an issue about those 3 stores (them not being singletons) so we can continue the discussion there.

Also, I just opened [this issue](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/2495) and assigned all us 3 to it for the time being.

Comment (ParaskP7) [reply fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginCoroutineStore.kt]: > I agree, I'll create an additional ticket for that too.

As discussed, I just opened [this issue](https://github.com/wordpress-mobile/WordPress-FluxC-Android/issues/2497) too and assigned us 2 to it (plus @aforcier, the initial and only author of this [rule and regex](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/trunk/config/checkstyle.xml#L84-L88).

Comment (irfano) [reply fluxc/src/main/java/org/wordpress/android/fluxc/store/PluginCoroutineStore.kt]: >I think for us to unblock this PR but still have this discussion going, I am going to revert this @Singleton change for now, merge this PR and open an issue about those 3 stores (them not being singletons) so we can continue the discussion there.

Good call.

Thanks for opening new issues.
