### PR TITLE
Primitive boolean deserializer

### LINKED ISSUE #9153: ParseError: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a boolean but was ...
Sentry Issue: [WOOCOMMERCE-ANDROID-5YF](https://a8c.sentry.io/issues/3923384523/?referrer=github_integration)

```
IllegalStateException: Expected a boolean but was NUMBER at line 1 column 3866 path $.data[0].purchasable
    at com.google.gson.stream.JsonReader.nextBoolean(JsonReader.java:864)
    at com.google.gson.internal.bind.TypeAdapters$3.read(TypeAdapters.java:146)
    at com.google.gson.internal.bind.TypeAdapters$3.read(TypeAdapters.java:135)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
...
(14 additional frame(s) were not displayed)

JsonSyntaxException: java.lang.IllegalStateException: Expected a boolean but was NUMBER at line 1 column 3866 path $.data[0].purchasable
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397)
    at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
    at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
...
(9 additional frame(s) were not displayed)

ParseError: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a boolean but was NUMBER at line 1 column 3866 path $.data[0].purchasable
    at org.wordpress.android.fluxc.network.rest.GsonRequest.parseNetworkResponse(GsonRequest.java:99)
    at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:144)
    at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
    at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

FluxC: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a boolean but was NUMBER at line 1 column 3866 path $.data[0].purchasable: API response parse error
```

### LINKED ISSUE #9154: ParseError: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a boolean but was ...
Sentry Issue: [WOOCOMMERCE-ANDROID-5YR](https://a8c.sentry.io/issues/3926617202/?referrer=github_integration)

```
IllegalStateException: Expected a boolean but was BEGIN_OBJECT at line 1 column 641 path $.data.purchasable
    at com.google.gson.stream.JsonReader.nextBoolean(JsonReader.java:864)
    at com.google.gson.internal.bind.TypeAdapters$3.read(TypeAdapters.java:146)
    at com.google.gson.internal.bind.TypeAdapters$3.read(TypeAdapters.java:135)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
...
(12 additional frame(s) were not displayed)

JsonSyntaxException: java.lang.IllegalStateException: Expected a boolean but was BEGIN_OBJECT at line 1 column 641 path $.data.purchasable
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:397)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393)
    at com.google.gson.Gson.fromJson(Gson.java:1227)
...
(7 additional frame(s) were not displayed)

ParseError: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a boolean but was BEGIN_OBJECT at line 1 column 641 path $.data.purchasable
    at org.wordpress.android.fluxc.network.rest.GsonRequest.parseNetworkResponse(GsonRequest.java:99)
    at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:144)
    at com.android.volley.NetworkDispatcher.processRequest(NetworkDispatcher.java:111)
    at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:90)

FluxC: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a boolean but was BEGIN_OBJECT at line 1 column 641 path $.data.purchasable: API response parse error
```

### PR DESCRIPTION
**Pull request by atorresveiga**
Closes: https://github.com/woocommerce/woocommerce-android/issues/9153
Closes: https://github.com/woocommerce/woocommerce-android/issues/9154

### Description
Some extensions (YITH WooCommerce Gift Cards, for example) change the type of the purchasable field to be an integer resulting in a [JsonSyntaxException](https://a8c.sentry.io/issues/3923384523/events/fd2a9bacec4b41e3ba2501400d232210/?project=1459556&referrer=next-event) when trying to deserialize a boolean, but an integer value was received instead. This PR tries to solve this issue by introducing a more resilience deserializer that will try to recover from the error and deserialize the purchasable field from primitives values (Boolean, Int, String)

### Testing Instructions
Unit tests should cover all the different scenarios

### CODE REVIEW

File: plugins/woocommerce/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/wc/product/PrimitiveBooleanJsonDeserializerTest.kt [hunk 1]
```diff
@@ -0,0 +1,177 @@
...
+        val result = sut.deserialize(
+            json = jsonElement,
+            typeOfT = null,
+            context = null
+        )
+        assertThat(result).isTrue
+    }
+
+    @Test
+    fun `when value is a number and is not 1 then false value is returned`() {
```
Comment (wzieba) [inline plugins/woocommerce/src/test/java/org/wordpress/android/fluxc/network/rest/wpcom/wc/product/PrimitiveBooleanJsonDeserializerTest.kt]:
```suggestion
    fun `when value is a number and is not 1 then null value is returned`() {
```

right?

**Review by wzieba — APPROVED** [review]
I liked the unit tests here, helped me understand the exact behavior right away 👏

**Comment by atorresveiga** [comment]
This PR also Closes: https://github.com/woocommerce/woocommerce-android/issues/9154
