### PR TITLE
Wrong id format

### LINKED ISSUE #9159: JsonSyntaxException: java.lang.NumberFormatException: For input string: "personalizedmessage"
Sentry Issue: [WOOCOMMERCE-ANDROID-6PQ](https://a8c.sentry.io/issues/4148332099/?referrer=github_integration)

```
NumberFormatException: For input string: "personalizedmessage"
    at jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2054)
    at jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
    at java.lang.Double.parseDouble(Double.java:543)
    at com.google.gson.stream.JsonReader.nextLong(JsonReader.java:977)
    at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:331)
...
(22 additional frame(s) were not displayed)

JsonSyntaxException: java.lang.NumberFormatException: For input string: "personalizedmessage"
    at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:333)
    at com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:323)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:433)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:393)
...
(18 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by atorresveiga**
Close https://github.com/woocommerce/woocommerce-android/issues/9159

### Description
This PR adds the new `JsonElementToLongSerializerDeserializer` to use on expected Long fields that could be modified by some extension returning a different type or an invalid value.

### Testing
Unit tests should cover all scenarios

### CODE REVIEW

File: plugins/woocommerce/src/test/java/org/wordpress/android/fluxc/utils/JsonElementToLongSerializerDeserializerTest.kt [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+            typeOfT = null,
+            context = null
+        )
+        assertThat(result).isEqualTo(value)
+    }
+
+    @Test
+    fun `test serialization deserialization`() {
+        val gsonBuilder = GsonBuilder()
+        val gson = gsonBuilder.registerTypeAdapter(Long::class.java, sut).create()
```
Comment (wzieba) [inline plugins/woocommerce/src/test/java/org/wordpress/android/fluxc/utils/JsonElementToLongSerializerDeserializerTest.kt]: What's the reason for registering Long adapter? I think it's not necessary 
```suggestion
        val gson = Gson()
```

**Review by wzieba — APPROVED** [review]
Looks good, added one comment
