### PR TITLE
Plugin Directory Pagination

### LINKED ISSUE #686: Pagination may not work for plugin directory
The `per_page` parameter is unreliable and doesn't always return the size requested which can mess up our current pagination (which is already a little fragile). I'll look into a better solution, but there is a chance that we might not be able to guarantee not to skip any items etc. We can only do so much without any changes in the API.

### PR DESCRIPTION
**Pull request by oguzkocer**
Fixes #686. I am keeping a checklist for the necessary changes/improvements in #690. I am aware that some things in this PR are not optimized, but that's by design as I am trying to focus on more urgent issues. Since we are merging this to a WIP branch and we are keeping a checklist of what's necessary, this should be fine.

This PR changes how the pagination is handled. Here is a little story to explain how it works and why it's done this way:

> The endpoint we are using for the plugin directory has `per_page` and `page` parameters. Unfortunately, there is no "give me plugins after this one" or "give me plugins before this one" parameters. It doesn't even have an `offset` parameter.
> 
> There are different type of directories ("new", "popular" etc) and a plugin can be in both directories. We also do single plugin fetches when we need more details for a particular plugin that's coming from a different endpoint. When you combine all these, it means we can't rely on a single table to be able to calculate the offset from. Also, if we were to use a single table, we would have ended up with multiple records for the same objects and having multiple sources of truth can be dangerous.
> 
> To get around this limitation, we separated the the information in 2 tables. `PluginDirectoryModelTable` and `WPOrgPluginModelTable`. The `WPOrgPluginModelTable` contains the actual data and `PluginDirectoryModelTable` contains the information about which data needs to be shown for each directory type.
> 
> The initial implementation was using the number of items in the `PluginDirectoryModelTable` for the directory type we are interested in to find out the offset and then calculate the page number. However, it turns out that `per_page` is only a suggestion for this endpoint. You might be asking for 50 items, but it'll only return 50 items on a good day. Otherwise, it might return 45, 48 etc. Sooo.. that approach doesn't really work.
> 
> I've then tried several fetch requests and tried to understand the pagination. I thought maybe we keep doubling the number of items we have to make sure we don't miss anything. Maybe we ask for the first 100 items, if we get 85 items, we ask for the next 85. I probably wouldn't use that approach, but I wanted to see how the api behaved. So, it turns out that the items have kind of like indexes and the next item actually is the 101th one, not the 86th one. I speculated that this is because the DB query probably gets everything then there is a filter (like give me the ones that are not deleted).
> 
> So, for this beatiful API, the best we can do is keep asking for the next page. This is easy to do if we want to involve WPAndroid in it, but we don't want to do that, so we need to save this information in our DB. We either save which page each item belongs to (`PluginDirectoryModelTable` page field) or we save in which page we are for each directory (separate table, one record for each directory type). I couldn't find any other way to do this, but I'd love to hear if there are any better ideas, because I hate this one :(

### CODE REVIEW

File: fluxc/src/main/java/org/wordpress/android/fluxc/model/plugin/PluginDirectoryType.java [hunk 1]
```diff
@@ -1,11 +1,13 @@
 package org.wordpress.android.fluxc.model.plugin;
 
+import java.util.Locale;
+
 public enum PluginDirectoryType {
     NEW,
     POPULAR;
 
     public String toString() {
```
Comment (nbradbury) [inline fluxc/src/main/java/org/wordpress/android/fluxc/model/plugin/PluginDirectoryType.java]: Should this be marked with an `@Override` annotation?

Comment (oguzkocer) [reply fluxc/src/main/java/org/wordpress/android/fluxc/model/plugin/PluginDirectoryType.java]: Fixed in 080ec1aa3a2b42763fa77bf1d4997ac97b9e8ac7

**Comment by oguzkocer** [comment]
@nbradbury That `@Override` issue is fixed. I've also removed the sections in a80b27548f2f091fe2ef6807108b092ebeb50ee1 as we discussed, so the long description, installation instructions etc doesn't affect us. Now, we should always start a single fetch for the full details in WPAndroid. Feel free to change that back if things become less responsive.

**Comment by nbradbury** [comment]
:shipit:
