### PR TITLE
Reduce `OrderEntity` payload before saving it

### LINKED ISSUE #2305: Filter out redundant data of `Order` before saving it into database
In order to fix issues with database queries exceeding Android's `Cursor` size, we want to reduce payload of the Order before saving it in local database. 

Some plugins add exceptionally large portion of, not needed in mobile app, data. For more details, please see internal communication at p91TBi-7qQ-p2.

### PR DESCRIPTION
**Pull request by wzieba**
Closes: #2305 

**Description**

This PR reduces payload of OrderEntities, raw `JSON` fields by filtering them before saving in database. For details, please see comments.

**Test cases**
See corresponding Woo PR for area of tests: https://github.com/woocommerce/woocommerce-android/pull/6020

### CODE REVIEW

File: plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/StripOrder.kt [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+import org.wordpress.android.fluxc.network.rest.wpcom.wc.order.OrderMappingConst.SHIPPING_PHONE_KEY
+import org.wordpress.android.fluxc.network.rest.wpcom.wc.order.OrderMappingConst.isNotInternalAttributeData
+import javax.inject.Inject
+
+internal class StripOrder @Inject constructor(private val gson: Gson) {
+    operator fun invoke(fatModel: OrderEntity): OrderEntity {
+        return fatModel.copy(
+                lineItems = gson.toJson(fatModel.getLineItemList().map { lineItemDto: LineItem ->
+                    lineItemDto.copy(
+                            metaData = lineItemDto.metaData?.filter { it.isNotInternalAttributeData }
```
Comment (wzieba) [inline plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/StripOrder.kt:16]: Logic taken from https://github.com/woocommerce/woocommerce-android/blob/trunk/WooCommerce/src/main/kotlin/com/woocommerce/android/model/Order.kt#L114

It was only applied to `attributesDescription` and not to `attributesList` but I can't find any attribute that could start with `_` and being used in app. Add-ons don't start with `_`, e.g:
image

Does it make sense to you? Or am I missing some case?

File: plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/StripOrder.kt [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+                    )
+                }),
+                shippingLines = gson.toJson(fatModel.getShippingLineList()),
+                feeLines = gson.toJson(fatModel.getFeeLineList()),
+                taxLines = gson.toJson(fatModel.getTaxLineList()),
+                metaData = gson.toJson(
+                        fatModel.getMetaDataList()
+                                .filter {
+                                            it.key == CHARGE_ID_KEY || it.key == SHIPPING_PHONE_KEY
```
Comment (wzieba) [inline plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/StripOrder.kt:25]: Logic taken from Woo codebase:

- `CHARGE_ID_KEY`: https://github.com/woocommerce/woocommerce-android/blob/trunk/WooCommerce/src/main/kotlin/com/woocommerce/android/model/Order.kt#L60-L61
- `SHIPPING_PHONE_KEY`: https://github.com/woocommerce/woocommerce-android/blob/trunk/WooCommerce/src/main/kotlin/com/woocommerce/android/ui/orders/shippinglabels/creation/CreateShippingLabelViewModel.kt#L433

Supplementary question: what's different with shipping phone passed in `OrderDto#Shipping#phone` vs the one from `MetaData`? @hichamboushaba do you remember maybe this case?

File: plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/StripOrder.kt [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+    operator fun invoke(fatModel: OrderEntity): OrderEntity {
+        return fatModel.copy(
+                lineItems = gson.toJson(fatModel.getLineItemList().map { lineItemDto: LineItem ->
+                    lineItemDto.copy(
+                            metaData = lineItemDto.metaData?.filter { it.isNotInternalAttributeData }
+                    )
+                }),
+                shippingLines = gson.toJson(fatModel.getShippingLineList()),
+                feeLines = gson.toJson(fatModel.getFeeLineList()),
+                taxLines = gson.toJson(fatModel.getTaxLineList()),
```
Comment (wzieba) [inline plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/StripOrder.kt:21]: The whole logic for reducing payload is to first pass it through our models so during this process, all unneeded data will be left behind. As we don't have domain models, this operations are performed between networking and database layers.
reduce_order

File: plugins/woocommerce/src/test/java/org/wordpress/android/fluxc/utils/JsonObjectBuilder.kt [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+import com.google.gson.JsonElement
+import com.google.gson.JsonObject
+import java.util.ArrayDeque
+import java.util.Deque
+
+internal fun json(build: JsonObjectBuilder.() -> Unit): JsonObject {
+    return JsonObjectBuilder().json(build)
+}
+
+internal class JsonObjectBuilder {
```
Comment (wzieba) [inline plugins/woocommerce/src/test/java/org/wordpress/android/fluxc/utils/JsonObjectBuilder.kt:13]: Internal, test only class for easier json DSL building.

**Comment by wzieba** [comment]
hi @hichamboushaba @nbradbury @ThomazFB 👋 . Github suggested your review as you recently edited files edited in this PR, I hope you don't mind 🙂. I'll request review also for corresponding PR on Woo side. Thanks!

**Comment by nbradbury** [comment]
@wzieba I did a first pass at this PR and all looks good, but given the size of the changes I'd definitely be more comfortable with another set of eyes on this. @hichamboushaba @ThomazFB

File: plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/StripOrder.kt (hunk 1 above)
Comment (ThomazFB) [reply plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/StripOrder.kt:16]: I'm not quite sure if we're missing something by doing this filter rule, but if that's the case, we're missing it from the start since this is the logic we're doing so far. And the `attributeList` property only gets attention from the Add-ons logic, so I guess it's safe.

File: plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderDtoMapper.kt [hunk 5]
```diff
@@ -1,34 +1,107 @@
...
+                company = this.company,
+                address_1 = this.address1,
+                address_2 = this.address2,
+                city = this.city,
+                state = this.state,
+                postcode = this.postcode,
+                country = this.country,
+                phone = this.phone
+        )
+    }
```
Comment (ThomazFB) [inline plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderDtoMapper.kt:106]: Not a change request, but more of a question: I have the feeling that these two extension methods could be in a standalone kt file instead of necessarily being part of a companion object since they're not accessed through the `OrderDtoMapper` but the receiving object instead. Do you think they should be defined like this? I'm just asking because these two methods described as it is can't even be called through a direct `OrderDtoMapper` access, so I don't see the benefit of them exist inside an object.

**Review by ThomazFB — APPROVED** [review]
Changes are looking good to me, it's well tested and the improvements look self-contained. Thanks for introducing this enhancement, @wzieba! I'll move to the Woo counterpart of this PR now.

File: plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderDtoMapper.kt (hunk 5 above)
Comment (wzieba) [reply plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/network/rest/wpcom/wc/order/OrderDtoMapper.kt:106]: True, we can move it to a different file. I'll handle this in next PR!
