### PR TITLE
Hide Scan Login Code when 2FA is active.

### LINKED ISSUE #17434: Hide Scan Login Code when logged into an account with 2FA
### Expected behavior
Expected not to see this option when logged into an account with 2FA, since Scan Login Code is not available for 2FA-enabled accounts.

### Actual behavior
Scan Login Code appears, leading me to believe I can use it. Then, when I try to use it to login to a WordPress.com site, I get an "Authentication Failed" message. This message encourages me to try scanning again.

### Steps to reproduce the behavior
1. Login to the Jetpack app with a WordPress.com account that has 2FA enabled.
2. In a web browser, open a browser or incognito tab where you're not logged into WordPress.com.
3. Head to WordPress.com > Login > Login via the Mobile App. Note the QR code is shown.
4. In the app, head to Me > Scan Login Code, and scan that QR code.
5. Note that authentication fails

Suggestion: Remove "Scan Login Code" from Me section when logged into an account with 2FA enabled.
Alternative: Adjust the "authentication failed" message to state that you cannot use QR code login for an account with 2FA enabled.

### PR DESCRIPTION
**Pull request by develric**
Fixes wordpress-mobile/WordPress-Android#17434 

This PR adds a new `mTwoStepEnabled` field and its management in the AccountModel/AccountRestClient + adds DB migration step.

It has a companion WP Android PR [here](https://github.com/wordpress-mobile/WordPress-Android/pull/17662) (please follow the instructions there for testing).

### CODE REVIEW

File: fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/account/AccountRestClient.java [hunk 1]
```diff
@@ -1174,6 +1175,10 @@ public static boolean updateAccountModelFromPushSettingsResponse(AccountModel ac
         if (from.containsKey("user_email_change_pending")) {
             accountModel.setPendingEmailChange((Boolean) from.get("user_email_change_pending"));
         }
+        if (from.containsKey("two_step_enabled")) {
+            Object twoStepEnabledValue = from.get("two_step_enabled");
+            accountModel.setTwoStepEnabled(twoStepEnabledValue != null && (Boolean) twoStepEnabledValue);
```
Comment (RenanLukas) [inline fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/account/AccountRestClient.java]: Super minor: should we check `instanceof` to see if the field is really a `Boolean` and if not, set it to `false` before casting it directly?

**Review by RenanLukas — APPROVED** [review]
Thanks for the changes, @develric . I've left a small comment (optional). LGTM :shipit:

File: fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/account/AccountRestClient.java (hunk 1 above)
Comment (develric) [reply fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/account/AccountRestClient.java]: I changed this @RenanLukas 🙇 . Please note I pushed a fix on the [WP companion PR](https://github.com/wordpress-mobile/WordPress-Android/pull/17662#issuecomment-1351624407). Ready for another pass 🙇
