### PR TITLE
Media uploading first fix

### LINKED ISSUE #370: Timeout issues uploading media
As reported in wp-android here https://github.com/wordpress-mobile/WordPress-Android/issues/5409#issuecomment-287333185 I'm having issue uploading media on WordPress.com. 

```
java.net.SocketTimeoutException: Read timed out 
at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:758)
```

The problem is with the Read timeout, that reaches the limit (without a valid reason) when uploading a "big" (>3MB) media file to the server. The size of the picture could vary, since I can reproduce the issue constantly on Android 7.1.1 with a 3MB file, but on another device with Android 5 I need to use pictures that are >5MB in size. Anyway the description of the issue I left on wp-android does have all the details.

A quick and partial solution to this issue would be to raise the default_read_timeout to 60 seconds in `MediaRestClient`. 
Note: Socket timeout in the old version of our networking layer was set 60 secs.

### PR DESCRIPTION
**Pull request by daniloercoli**
Fix #370 by setting the read_timeout to 60secs.

Not sure how you can reproduce the issue, but you could try by uploading big pictures or videos to your dotcom blog. All the details in the ticket.

### CODE REVIEW

File: fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/media/MediaRestClient.java [hunk 1]
```diff
@@ -70,7 +70,7 @@ public MediaRestClient(Context appContext, Dispatcher dispatcher, RequestQueue r
         super(appContext, dispatcher, requestQueue, accessToken, userAgent);
         mOkHttpClient = okClientBuilder
                 .connectTimeout(BaseRequest.DEFAULT_REQUEST_TIMEOUT, TimeUnit.MILLISECONDS)
-                .readTimeout(BaseRequest.DEFAULT_REQUEST_TIMEOUT, TimeUnit.MILLISECONDS)
+                .readTimeout(BaseRequest.DEFAULT_REQUEST_READ_TIMEOUT, TimeUnit.MILLISECONDS)
```
Comment (maxme) [inline fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/media/MediaRestClient.java]: Can you rename this `DEFAULT_REQUEST_READ_TIMEOUT` to `UPLOAD_REQUEST_READ_TIMEOUT`, and also reuse it in `MediaXMLRPCClient`?

**Comment by daniloercoli** [comment]
Renamed and used in both the REST and XML-RPC clients.

**Comment by maxme** [comment]
:shipit:
