### PR TITLE
Fix isAdmin flag for .com sites

### LINKED ISSUE #95: SiteStore: it seems isAdmin is always false for .com sites

### PR DESCRIPTION
**Pull request by oguzkocer**
Fixes #95. The `isAdmin` flag was never set for wp.com sites. As mentioned in the comment, only admins can have `manage_options` capability on wp.com sites, so we can simply use that to set the flag. I also threw in a small code re-order to match the UI.

### CODE REVIEW

**Comment by maxme** [comment]
I'm not sure that's the best option to solve this. Looking at the table [here](https://codex.wordpress.org/Roles_and_Capabilities#manage_options) there are many other `manage_` capabilities that could be off for an administrator. 

Maybe the best option is just to ask the API devs why there is no such field and depending of their answer, we could maybe drop that field even for self hosted (if we're able to pull user's capabilities).

**Comment by oguzkocer** [comment]
@maxme As far as I know from the previous discussions on People Management feature, the capabilities of roles are set for wp.com sites. I agree that this is not a good option for self-hosted, but it should be totally fine for .com.

Having said that, I agree that it'd be better to just drop the field all together for .com sites, but I don't think there was a way to get capabilities of self-hosted sites. I kind of wish we separated the 2 models..

**Comment by oguzkocer** [comment]
How about this? We can remove the field and manually assign capabilities to self-hosted if the user is an admin or we rename the field to something like `isSelfHostedAdmin` and just don't use and set it for .com sites. I like the second option the most even more than current implementation in the PR. What do you think @maxme ?

**Comment by maxme** [comment]
> we rename the field to something like isSelfHostedAdmin and just don't use and set it for .com sites

Yes, that's better IMO. Also I had a look how `site.isAdmin()` is used in the app and I think we can remove all the calls.

**Comment by oguzkocer** [comment]
@maxme I've changed the `isAdmin` field to `isSelfHostedAdmin` and made the relevant changes. Once this is merged I can switch to wpandroid integration branch and fix the usages there as well.

File: fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.java [hunk 1]
```diff
@@ -380,16 +380,14 @@ public boolean isWPComSiteVisibleByLocalId(int id) {
     }
 
     /**
-     * Checks whether the user is an admin of the given (remote) site id.
+     * Checks whether the user is an admin of the given (remote) self hosted site id.
      */
-    public boolean isCurrentUserAdminOfSiteId(long siteId) {
+    public boolean isCurrentUserAdminOfSelfHostedSiteId(long selfHostedSiteId) {
```
Comment (maxme) [inline fluxc/src/main/java/org/wordpress/android/fluxc/store/SiteStore.java]: We can drop this method completely, it's not used anymore in wpandroid
