### PR TITLE
Fix #339: Handle site fetch response for VIP sites

### LINKED ISSUE #339: Deal with 'vip' plans response to FETCH_SITES
VIP sites will have [`product_id = 'vip'` rather than a number](https://github.com/wordpress-mobile/WordPress-FluxC-Android/blob/bc85f40f958b228cdc2093cb855ae72f08aa7271/fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteWPComRestResponse.java#L23), which causes a (handled) `NumberFormatException` and sites are not stored.

### PR DESCRIPTION
**Pull request by aforcier**
Fixes #339. VIP sites return a String `product_id` (`'vip'`) rather than a number. This caused a handled `NumberFormatException`, resulting in no WP.com sites being fetched.

### CODE REVIEW

File: fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteWPComRestResponse.java [hunk 1]
```diff
@@ -6,6 +6,8 @@
 import java.util.List;
 
 public class SiteWPComRestResponse extends Payload implements Response {
+    public static final long VIP_PLAN_ID = 31337;
```
Comment (maxme) [inline fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteWPComRestResponse.java]: I wonder if we should move that to the SiteModel, in case we want to use it in the app, it makes more sense to `site.getProductId() == SiteModel.VIP_PLAN_ID`

**Comment by maxme** [comment]
I confirm this fixes the issue VIP users were getting on sign in.

**Comment by maxme** [comment]
Ready to 🚢 / waiting for @aforcier reply to https://github.com/wordpress-mobile/WordPress-FluxC-Android/pull/340#discussion_r103857062

File: fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteWPComRestResponse.java (hunk 1 above)
Comment (aforcier) [inline fluxc/src/main/java/org/wordpress/android/fluxc/network/rest/wpcom/site/SiteWPComRestResponse.java]: Makes sense, done in 3dde283.

**Comment by maxme** [comment]
:shipit:
