### PR TITLE
Fix race condition when inserting/updating products and related classes

### LINKED ISSUE #10349: IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and ...
Sentry Issue: [WOOCOMMERCE-ANDROID-4X4](https://a8c.sentry.io/issues/3590019606/?referrer=github_integration)

```
IllegalStateException: Two different ViewHolders have the same stable ID. Stable IDs in your adapter MUST BE unique and SHOULD NOT change.
 ViewHolder 1:ProductItemViewHolder{f06304e position=5 id=136915, oldPos=-1, pLpos:-1 not recyclable(1)} 
 View Holder 2:ProductItemViewHolder{fac9452 position=4 id=136915, oldPos=-1, pLpos:-1} androidx.recyclerview.widget.RecyclerView{b75696 VFED..... ......ID 0,180-1080,1842 #7f0a085e app:id/productsRecycler}, adapter:com.woocommerce.android.ui.products.ProductListAdapter@547623, layout:androidx.recyclerview.widget.LinearLayoutManager@1ee3ba4, context:dagger.hilt.android.internal.managers.ViewComponentManager$FragmentContextWrapper@c37ead5
    at androidx.recyclerview.widget.RecyclerView.handleMissingPreInfoForChangeError(RecyclerView.java:4778)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:4702)
    at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:4367)
    at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4919)
    at android.view.View.layout(View.java:24969)
...
(67 additional frame(s) were not displayed)
```

### PR DESCRIPTION
**Pull request by hichamboushaba**
This PR is an attempt to fix https://github.com/woocommerce/woocommerce-android/issues/10349, it adds logic to make sure the batch write operations are executed in transactions.

Let's not merge this yet until we decide if we need to release this in a beta fix or not.

Test instructions are on https://github.com/woocommerce/woocommerce-android/pull/10373

### CODE REVIEW

File: plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/ProductSqlUtils.kt [hunk 1]
```diff
@@ -846,6 +856,18 @@ object ProductSqlUtils {
         }
     }
 
+    private fun executeInTransaction(block: () -> Unit) {
```
Comment (AnirudhBhat) [inline plugins/woocommerce/src/main/kotlin/org/wordpress/android/fluxc/persistence/ProductSqlUtils.kt:859]: ❤️

**Review by AnirudhBhat — APPROVED** [review]
Excellent work here @hichamboushaba. LGTM! :shipit:

**Comment by hichamboushaba** [comment]
@AnirudhBhat since we decided we'll include this as a beta fix peaMlT-k5-p2#comment-740, I updated the base branch to the release one, I'm going to merge this PR now and then create a new tag 2.59.1 that we'll use in the beta fix.
